on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18.18.2
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install
      - run: node App.js